version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Install phase complete"

  build:
    commands:
      - echo "Zipping Lambda code"
      - zip -r lambda.zip . -x ".git/*" "buildspec.yml"

  post_build:
    commands:
      - echo "Deploying to Lambda testing_hotel_minerva"
      - aws lambda update-function-code --function-name testing_hotel_minerva --zip-file fileb://lambda.zip

