version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "No dependency installation required (using Lambda Layers)"

  build:
    commands:
      - echo "Preparing deployment package"
      - zip -r lambda.zip . -x "*.git*" "buildspec.yml"

  post_build:
    commands:
      - echo "Deploying to Lambda function: testing_hotel_minerva"
      - aws lambda update-function-code \
          --function-name testing_hotel_minerva \
          --zip-file fileb://lambda.zip

artifacts:
  files:
    - lambda.zip
